# build .net assemblies (Common, Tests, OnlineTrainer)
name: Build Assemblies

on:
  workflow_run:
    workflows: ["Build Binary Parser"]
    types:
      - completed

env:
  BUILD_ARTIFACTS_CACHE: ${{github.workspace}}/artifacts

jobs:
  build-assemblies:
    name: assemblies-${{ matrix.build.build_type }}-${{ matrix.config.os_name }}
    runs-on: ${{ matrix.config.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "windows-latest", os_name: "windows-latest" }
          - { os: "ubuntu-latest", os_name: "ubuntu-latest" }
          - { os: "macos-13", os_name: "macos-latest" }
        build:
          - { build_type: "debug" }
          - { build_type: "release" }

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.head_ref || github.ref }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore Binary Parser Binaries
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_ARTIFACTS_CACHE }}
          key: learning-loop-${{ github.event.workflow_run.outputs.cache_key }}-artifacts

      - name: Build Common
        run: dotnet build -c ${{ matrix.build.build_type }} Common/Common.csproj -p:CIVWBinParserPath=${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.build.build_type }}/vw-bin
      - name: Build OnlineTrainer
        run: dotnet build -c ${{ matrix.build.build_type }} OnlineTrainerExe/OnlineTrainerExe.csproj -p:CIVWBinParserPath=${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.build.build_type }}/vw-bin
      - name: Build Tests
        run: dotnet build -c ${{ matrix.build.build_type }} Tests/Tests.csproj -p:CIVWBinParserPath=${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.build.build_type }}/vw-bin

      - name: Publish Common
        run: dotnet publish --no-build -c ${{ matrix.build.build_type }} Common/Common.csproj -o ${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.config.os_name }}/${{ matrix.build.build_type }}/Common
      - name: Publish OnlineTrainer
        run: dotnet publish --no-build -c ${{ matrix.build.build_type }} OnlineTrainerExe/OnlineTrainerExe.csproj -o ${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.config.os_name }}/${{ matrix.build.build_type }}/OnlineTrainer
      - name: Publish Tests
        run: dotnet publish -c ${{ matrix.build.build_type }} Tests/Tests.csproj -o ${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.config.os_name }}/${{ matrix.build.build_type }}/Tests -p:CIVWBinParserPath=${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.build.build_type }}/vw-bin

      - name: Cache binaries
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_ARTIFACTS_CACHE }}
          key: learning-loop-${{ github.event.workflow_run.outputs.cache_key }}-artifacts
