# build .net assemblies (Common, Tests, OnlineTrainer)
name: Build Assemblies

on:
  workflow_run:
    workflows: ["Build Binary Parser"]
    types:
      - completed

env:
  BUILD_ARTIFACTS_CACHE: ${{github.workspace}}/artifacts

jobs:
  build-assemblies:
    name: assemblies-${{ matrix.build.build_type }}-${{ matrix.config.os_name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "windows-latest", os_name: "windows-latest" }
          - { os: "ubuntu-latest", os_name: "ubuntu-latest" }
          - { os: "macos-13", os_name: "macos-latest" }
        build:
          - { build_type: "debug" }
          - { build_type: "release" }

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore Binary Parser Binaries
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_ARTIFACTS_CACHE }}
          key: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-artifacts

      - name: Build VW Resolver
        run: dotnet build -c ${{ matrix.build.build_type }} VWBinResolver/VWBinResolver.csproj -p:CIVWBinParserPath=${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.build.build_type }}/vw-bin
      - name: Build Flatbuffers
        run: dotnet build -c ${{ matrix.build.build_type }} Flatbuffers/Flatbuffers.csproj
      - name: Build Common
        run: dotnet build -c ${{ matrix.build.build_type }} Common/Common.csproj
      - name: Build OnlineTrainer
        run: dotnet build -c ${{ matrix.build.build_type }} OnlineTrainerExe/OnlineTrainerExe.csproj
      - name: Build CommonTest
        run: dotnet build -c ${{ matrix.build.build_type }} CommonTest/CommonTest.csproj
      - name: Build TestExeApp
        run: dotnet build -c ${{ matrix.build.build_type }} TestExeApp/TestExeApp.csproj
      - name: Build Tests
        run: dotnet build -c ${{ matrix.build.build_type }} Tests/Tests.csproj

      - name: Publish Common
        run: dotnet publish --no-build -c ${{ matrix.build.build_type }} Common/Common.csproj -o ${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.config.os_name }}/${{ matrix.build.build_type }}/Common
      - name: Publish OnlineTrainer
        run: dotnet publish --no-build -c ${{ matrix.build.build_type }} OnlineTrainerExe/OnlineTrainerExe.csproj -o ${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.config.os_name }}/${{ matrix.build.build_type }}/OnlineTrainer
      - name: Publish Tests
        run: dotnet publish -c ${{ matrix.build.build_type }} Tests/Tests.csproj -o ${{ env.BUILD_ARTIFACTS_CACHE }}/${{ matrix.config.os_name }}/${{ matrix.build.build_type }}/Tests

      - name: Cache binaries
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_ARTIFACTS_CACHE }}
          key: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-artifacts
